# =============================================================================
# VectorPlane GCP Onboarding - Terraform Module Variables
# =============================================================================
# This module establishes a Workload Identity Federation trust between
# VectorPlane (AWS-hosted) and your GCP environment. Zero long-lived secrets.
# =============================================================================

# -----------------------------------------------------------------------------
# Required Variables (Provided by VectorPlane UI)
# -----------------------------------------------------------------------------

variable "external_id" {
  description = "Unique session ID generated by VectorPlane for this onboarding session"
  type        = string

  validation {
    condition     = length(var.external_id) >= 10
    error_message = "external_id must be at least 10 characters (session ID format)"
  }
}

variable "webhook_secret" {
  description = "HMAC secret for webhook signature verification (provided by VectorPlane)"
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.webhook_secret) >= 32
    error_message = "webhook_secret must be at least 32 characters for security"
  }
}

variable "gcp_scope_id" {
  description = "GCP Project ID, Organization ID, or Folder ID. Empty = auto-detect from Cloud Shell context (PROJECT scope only)"
  type        = string
  default     = ""

  validation {
    # Allow: empty, project ID (lowercase letters/numbers/hyphens), org ID (numeric), or folder ID (folders/numeric)
    condition = (
      var.gcp_scope_id == "" ||
      can(regex("^[a-z][a-z0-9-]{4,28}[a-z0-9]$", var.gcp_scope_id)) ||
      can(regex("^[0-9]+$", var.gcp_scope_id)) ||
      can(regex("^folders/[0-9]+$", var.gcp_scope_id))
    )
    error_message = "gcp_scope_id must be empty (auto-detect), a valid GCP project ID, numeric organization ID, or folders/123 format"
  }
}

# -----------------------------------------------------------------------------
# Scope Configuration
# -----------------------------------------------------------------------------

variable "onboarding_scope" {
  description = "Scope of access: PROJECT (single project), FOLDER (projects in folder), or ORGANIZATION (all projects)"
  type        = string
  default     = "PROJECT"

  validation {
    condition     = contains(["PROJECT", "FOLDER", "ORGANIZATION"], var.onboarding_scope)
    error_message = "onboarding_scope must be PROJECT, FOLDER, or ORGANIZATION"
  }
}

variable "organization_id" {
  description = "GCP Organization ID (required if onboarding_scope is ORGANIZATION)"
  type        = string
  default     = ""

  validation {
    condition     = var.organization_id == "" || can(regex("^[0-9]+$", var.organization_id))
    error_message = "organization_id must be a numeric string if provided"
  }
}

# -----------------------------------------------------------------------------
# VectorPlane Infrastructure (Defaults - Do Not Change)
# -----------------------------------------------------------------------------

variable "vectorplane_aws_account_id" {
  description = "VectorPlane's AWS account ID for WIF trust relationship"
  type        = string
  default     = "101460827772"
}

variable "vectorplane_aws_role_name" {
  description = "VectorPlane's AWS IAM role name that will assume GCP identity"
  type        = string
  default     = "VectorPlaneWorker"
}

variable "vectorplane_callback_url" {
  description = "VectorPlane webhook URL for setup completion notification"
  type        = string
  default     = "https://api.vectorplane.io/api/v1/webhooks/gcp-connect"
}

# -----------------------------------------------------------------------------
# Resource Naming (Customizable)
# -----------------------------------------------------------------------------

variable "wif_pool_id" {
  description = "Workload Identity Pool ID"
  type        = string
  default     = "vectorplane-security-pool"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{2,30}[a-z0-9]$", var.wif_pool_id))
    error_message = "wif_pool_id must be 4-32 lowercase letters, numbers, hyphens"
  }
}

variable "wif_provider_id" {
  description = "Workload Identity Pool Provider ID"
  type        = string
  default     = "vectorplane-aws-provider"
}

variable "service_account_id" {
  description = "Service Account ID for VectorPlane to impersonate"
  type        = string
  default     = "vectorplane-security"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{4,28}[a-z0-9]$", var.service_account_id))
    error_message = "service_account_id must be 6-30 lowercase letters, numbers, hyphens"
  }
}

# -----------------------------------------------------------------------------
# Feature Flags
# -----------------------------------------------------------------------------

variable "enable_folder_discovery" {
  description = "Grant permissions for folder hierarchy discovery (recommended for ORGANIZATION scope)"
  type        = bool
  default     = true
}

variable "enable_state_file_access" {
  description = "Grant GCS read access for Terraform state file verification"
  type        = bool
  default     = true
}

# -----------------------------------------------------------------------------
# Dev-Mode OIDC Bridge (Local Testing Only)
# -----------------------------------------------------------------------------

variable "project_id" {
  description = "GCP project ID from VectorPlane context (informational, not used by module)"
  type        = string
  default     = ""
}

variable "dev_oidc_issuer_url" {
  description = "Mock OIDC issuer URL for dev-mode WIF testing. Leave empty for production."
  type        = string
  default     = ""
}
